
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    namespace: default
    labels:
      name: wd
      version: 0.0.1
    name: wd
  spec:
    ports:
    - name: ui
      port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      app: wd
    sessionAffinity: None
    type: LoadBalancer